name: gpa_calculator
description: A comprehensive GPA calculator app with dark mode support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management & storage
  shared_preferences: ^2.2.2

  # UI
  cupertino_icons: ^1.0.6
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/ada_logo.png"
  adaptive_icon_background: "#0B264C"
  adaptive_icon_foreground: "assets/logo/ada_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/